[theme]
primaryColor="#0096C7"
backgroundColor="#F0F2F6"
secondaryBackgroundColor="#FFFFFF"
textColor="#343A40"
font="sans serif"

[server]
# port = 8501
# headless = true
# enableCORS = false
# enableXsrfProtection = true

[browser]
gatherUsageStats = false

[logger]
level = "info"

[runner]
# magicEnabled = true
# fastReruns = true

[global]
# dataFrameSerialization = "legacy"
