OPENROUTER_API_KEY = "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"

# Example of other potential secrets:
# DB_USERNAME = "your_db_user"
# DB_PASSWORD = "your_db_password"
# OTHER_API_KEY = "another_secret_key"
